### ISSUE TITLE
stream-lnd-htlcs-bot.service: Start request repeated too quickly

### ISSUE THREAD

**Issue by Deekee62** [PLEBNET-PLAYGROUND/stream-lnd-htlcs-bot#5]
After a failure of stream-lnd-htlcs-bot.service, for whatever reason, the service fails to restart successfully  after 5 retries as it's restarted to quickly.

```
Sep 27 05:55:12 umbrel systemd[1]: Started Stream LND HTLCS Service.
Sep 27 05:55:13 umbrel systemd[1]: stream-lnd-htlcs.service: Main process exited, code=exited, status=1/FAILURE                                                                                          
Sep 27 05:55:13 umbrel systemd[1]: stream-lnd-htlcs.service: Failed with result 'exit-code'.
Sep 27 05:55:13 umbrel systemd[1]: stream-lnd-htlcs.service: Service RestartSec=100ms expired, scheduling restart.                                                                                       
Sep 27 05:55:13 umbrel systemd[1]: stream-lnd-htlcs.service: Scheduled restart job, restart counter is at 5.                                                                                             
Sep 27 05:55:13 umbrel systemd[1]: Stopped Stream LND HTLCS Service.
Sep 27 05:55:13 umbrel systemd[1]: stream-lnd-htlcs.service: Start request repeated too quickly.
Sep 27 05:55:13 umbrel systemd[1]: stream-lnd-htlcs.service: Failed with result 'exit-code'.
Sep 27 05:55:13 umbrel systemd[1]: Failed to start Stream LND HTLCS Service.
```

As systemd defaults to 100ms I would suggest to add the following entry: `RestartSec=1` in the file [https://github.com/PLEBNET-PLAYGROUND/stream-lnd-htlcs-bot/blob/master/confs/stream-lnd-htlcs-bot.service](https://github.com/PLEBNET-PLAYGROUND/stream-lnd-htlcs-bot/blob/master/confs/stream-lnd-htlcs-bot.service)

[Service]
Type=simple
Restart=always
**RestartSec=1**
WorkingDirectory=/home/umbrel/stream-lnd-htlcs-bot

**Comment by rsafier** [comment]
well if anything you probably want even larger restart delay and make it infinite restart (as you really never know when the service till become available)
Another option would be modifying the python to just run a loop waiting for the gRPC interfaces to become ready.
I'm simply hosting this repo, not really maintaining it beyond accepting PRs. So feel free to offer a PR.
